title: Python Blogs
description: "August 2023 to June 2024"
gitorg: https://github.com/nighthawkcoders/python-pages
gitpages: https://nighthawkcoders.github.io/python-pages
owner_name: Nighthawk Coders
theme: jekyll-theme-midnight
